# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 首席干饭王的小屋
subtitle: '干饭人，干饭魂，干饭都是人上人'
description: ''
keywords: PHP博客，技术博客，好看的博客，go基础教程
author: 上官铁柱的翠花
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yun

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:  https://github.com/peate-cabin/peate-cabin.github.io # 比如：https://github.com/YunYouJun/yunyoujun.github.io
  branch: master # 默认使用 master 分支
  message: 提交静态文件 # 你可以自定义此次部署更新的说明

#2d人物
#live2d:
#  enable: true
#  # enable: false
#  pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
#  pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
#  pluginModelPath: assets/ # Relative model path related to plugin's root (Relative)
#  scriptFrom: local # Default
#  # scriptFrom: jsdelivr # jsdelivr CDN
#  # scriptFrom: unpkg # unpkg CDN
#  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # Your custom url
#  tagMode: false # Whether only to replace live2d tag instead of inject to all pages
#  log: false # Whether to show logs in console
#  model:
#    use: live2d-widget-model-shizuku # npm-module package name
#  display:
#    superSample: 2
#    width: 200
#    height: 300
#    position: right # 模型在网页显示位置
#    hOffset: 20
#    vOffset: 60
#  mobile:
#    show: true  # 移动设备是否显示
#    scale: 0.5
#  react:
#    opacityDefault: 0.7

live2d:
  enable: true
  # 推荐使用 jsdelivr 的 CDN 来加载
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # 推荐使用 CDN 来加载模型
    use: https://cdn.jsdelivr.net/npm/live2d-widget-model-hibiki@1.0.5/assets/hibiki.model.json
  display:
    position: right
    width: 150
    height: 300
    hOffset: 20
    vOffset: 60
  mobile:
    show: true
    scale: 0.5
  react:
    opacity: 0.7
  dialog:
    # 是否开启对话框
    enable: true
    # 是否使用一言
    hitokoto: true

#音乐播放器
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@1/dist/Meting.min.js

